- name: Base installs - update & upgrade
  hosts: masters
  become: true
  roles:
    - base


- name: Deploy PiHole DNS filtering
  hosts: masters
  become: true
  roles:
    - dns-filter


- name: Deploy Caddy reverse proxy
  hosts: masters
  become: true
  roles:
    - reverse-proxy