ansible_host: 192.168.2.253
WEBPASSWORD: test
PIHOLE_INTERFACE: eth0
IPV4_ADDRESS: 192.168.2.253/24
IPV6_ADDRESS: 2601:444:8111:403:55d6:2f11:41bf:13bb
QUERY_LOGGING: true
INSTALL_WEB: true
DNSMASQ_LISTENING: single


DNS_FQDN_REQUIRED: true
DNS_BOGUS_PRIV: true
DNSSEC: true
TEMPERATUREUNIT: C
WEBUIBOXEDLAYOUT: traditional
pihole_webserver_port: "8080,[::]:8080"

pihole_adlists:
  - address: https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt
    comment: Managed by Ansible - KADhosts
  - address: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts
    comment: Managed by Ansible - FadeMind Spam
  - address: https://v.firebog.net/hosts/static/w3kbl.txt
    comment: Managed by Ansible - Firebog w3kbl
  - address: https://adaway.org/hosts.txt
    comment: Managed by Ansible - AdAway
  - address: https://v.firebog.net/hosts/AdguardDNS.txt
    comment: Managed by Ansible - AdGuard DNS
  - address: https://v.firebog.net/hosts/Admiral.txt
    comment: Managed by Ansible - Admiral
  - address: https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
    comment: Managed by Ansible - anudeepND
  - address: https://v.firebog.net/hosts/Easylist.txt
    comment: Managed by Ansible - EasyList
  - address: https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
    comment: Managed by Ansible - yoyo
  - address: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts
    comment: Managed by Ansible - UncheckyAds
  - address: https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts
    comment: Managed by Ansible - hostsVN
  - address: https://v.firebog.net/hosts/Easyprivacy.txt
    comment: Managed by Ansible - EasyPrivacy
  - address: https://v.firebog.net/hosts/Prigent-Ads.txt
    comment: Managed by Ansible - Prigent Ads
  - address: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts
    comment: Managed by Ansible - 2o7Net
  - address: https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
    comment: Managed by Ansible - WindowsSpyBlocker
  - address: https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt
    comment: Managed by Ansible - Frogeye
  - address: https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
    comment: Managed by Ansible - AntiMalwareHosts
  - address: https://v.firebog.net/hosts/Prigent-Crypto.txt
    comment: Managed by Ansible - Prigent Crypto
  - address: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts
    comment: Managed by Ansible - Risk
  - address: https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt
    comment: Managed by Ansible - Mandiant APT1
  - address: https://phishing.army/download/phishing_army_blocklist_extended.txt
    comment: Managed by Ansible - Phishing Army
  - address: https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt
    comment: Managed by Ansible - NoTrack Malware
  - address: https://v.firebog.net/hosts/RPiList-Malware.txt
    comment: Managed by Ansible - RPiList Malware
  - address: https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt
    comment: Managed by Ansible - Spam404
  - address: https://raw.githubusercontent.com/AssoEchap/stalkerware-indicators/master/generated/hosts
    comment: Managed by Ansible - Stalkerware Indicators
  - address: https://urlhaus.abuse.ch/downloads/hostfile/
    comment: Managed by Ansible - URLhaus
  - address: https://lists.cyberhost.uk/malware.txt
    comment: Managed by Ansible - Cyberhost Malware

caddy_sites:
  - hostname: jellyfin.home
    schemes:
      - http
      - https
    upstream: 192.168.2.179:8096
    tls_internal: true
    comment: Jellyfin reverse proxy (local network only)
  - hostname: pihole.home
    schemes:
      - http
      - https
    upstream: 127.0.0.1:8080
    comment: Pi-hole reverse proxy (local network only)
    redirect_root_to: /admin
    tls_internal: true
  - hostname: abs.home
    schemes:
      - http
      - https
    upstream: 192.168.2.179:13378
    tls_internal: true
    comment: AudioBookShelf reverse proxy (local network only)
  - hostname: prowlarr.home
    schemes:
      - http
      - https
    upstream: 192.168.2.179:9696
    tls_internal: true
    comment: Prowlarr reverse proxy (local network only)
  - hostname: radarr.home
    schemes:
      - http
      - https
    upstream: 192.168.2.179:7878
    tls_internal: true
    comment: Radarr reverse proxy (local network only)
  - hostname: sonarr.home
    schemes:
      - http
      - https
    upstream: 192.168.2.179:8989
    tls_internal: true
    comment: Sonarr reverse proxy (local network only)
  - hostname: qbittorent.home
    schemes:
      - http
      - https
    upstream: 192.168.2.179:9080
    tls_internal: true
    comment: qbittorent reverse proxy (local network only)
  - hostname: bazarr.home
    schemes:
      - http
      - https
    upstream: 192.168.2.179:6767
    tls_internal: true
    comment: Bazarr reverse proxy (local network only)
  - hostname: grafana.home
    schemes:
      - http
      - https
    upstream: 192.168.2.179:3001
    tls_internal: true
    comment: Grafana reverse proxy (local network only)
  - hostname: index.home
    schemes:
      - http
      - https
    upstream: 192.168.2.179:1111
    tls_internal: true
    comment: Index page reverse proxy (local network only)
  - hostname: komga.home
    schemes:
      - http
      - https
    upstream: 192.168.2.179:25600
    tls_internal: true
    comment: Komga reverse proxy (local network only)
  - hostname: nextcloud.home
    schemes:
      - http
      - https
    upstream: 192.168.2.179:8000
    tls_internal: true
    comment: Nextcloud reverse proxy (local network only)
  - hostname: ntfy.home
    schemes:
      - http
      - https
    upstream: 192.168.2.179:8090
    tls_internal: true
    comment: NTFY reverse proxy (local network only)
  - hostname: tandoor.home
    schemes:
      - http
      - https
    upstream: 192.168.2.179:8081
    tls_internal: true
    comment: Tandoor reverse proxy (local network only)
  - hostname: immich.home
    schemes:
      - http
      - https
    upstream: 192.168.2.179:2283
    tls_internal: true
    comment: Immich reverse proxy (local network only)
  - hostname: vaultwarden.home
    schemes:
      - http
      - https
    upstream: 192.168.2.179:8080
    tls_internal: true
    comment: Vaultwarden reverse proxy (local network only)

pihole_local_dns_records:
  - hostname: jellyfin.home
    ip: 192.168.2.253
  - hostname: pihole.home
    ip: 192.168.2.253
  - hostname: abs.home
    ip: 192.168.2.253
  - hostname: prowlarr.home
    ip: 192.168.2.253
  - hostname: radarr.home
    ip: 192.168.2.253
  - hostname: sonarr.home
    ip: 192.168.2.253
  - hostname: qbittorent.home
    ip: 192.168.2.253
  - hostname: bazarr.home
    ip: 192.168.2.253
  - hostname: grafana.home
    ip: 192.168.2.253
  - hostname: index.home
    ip: 192.168.2.253
  - hostname: komga.home
    ip: 192.168.2.253
  - hostname: nextcloud.home
    ip: 192.168.2.253
  - hostname: ntfy.home
    ip: 192.168.2.253
  - hostname: tandoor.home
    ip: 192.168.2.253
  - hostname: immich.home
    ip: 192.168.2.253
  - hostname: vaultwarden.home
    ip: 192.168.2.253
