- name: Update apt-get repo and cache
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600


- name: Upgrade all apt packages
  become: true
  ansible.builtin.apt:
    upgrade: dist